all:
	echo aaa

aaa:
	cat \
	lib/header.js \
	../jsrsasign-latest-all-min.js \
	../../../../jsjws/_gitpg/jsjws/ext/json-sans-eval-min.js \
	../../../../jsjws/_gitpg/jsjws/jws-3.0.min.js \
	../../../../jsjws/_gitpg/jsjws/jwsjs-2.0.min.js \
	lib/footer.js \
	> lib/jsrsasign.js

